// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ingestion.proto
// Original file comments:
//
// ingestion.proto
//
// Contains methods and data types specific to the Ingestion Service.
//
#ifndef GRPC_ingestion_2eproto__INCLUDED
#define GRPC_ingestion_2eproto__INCLUDED

#include "ingestion.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace dp {
namespace service {
namespace ingestion {

//
// ------------------- RPC Interfaces ---------------------------
//
//
//
// The Ingestion Service Interface
//
// Defines RPC operations for data provider registration and ingestion.
//
class DpIngestionService final {
 public:
  static constexpr char const* service_full_name() {
    return "dp.service.ingestion.DpIngestionService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    //
    // registerProvider(): Data provider registration.
    //
    // This unary method sends a single RegisterProviderRequest and receives a single RegisterProviderResponse.  It is
    // required to call this method to register a data provider before calling one of the data ingestion methods using
    // the id of that provider.
    //
    // Provider name is required in the RegisterProviderRequest, which may also contain optional metadata key/value
    // attributes describing the provider.
    //
    // The response message indicates whether or not the registration was successful.  The response payload is an
    // ExceptionalResult if the request is unsuccessful, otherwise it is a RegistrationResult that includes details about
    // the new provider including providerId (for use in calls to data ingestion methods) and a flag indicating if the
    // provider is new.  On success, if a document already exists in the MongoDB "providers" collection for the provider
    // name specified in the RegisterProviderRequest, the method returns the corresponding provider id in the response,
    // otherwise a new document is created in the "providers" collection and its id returned in the response.
    //
    // It is safe (and recommended) to call this method each time a data ingestion client is run.  If a document already
    // exists in the MongoDB providers collection for the specified provider, the attributes are updated to the values in
    // the RegisterProviderRequest.
    virtual ::grpc::Status registerProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::dp::service::ingestion::RegisterProviderResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::RegisterProviderResponse>> AsyncregisterProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::RegisterProviderResponse>>(AsyncregisterProviderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::RegisterProviderResponse>> PrepareAsyncregisterProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::RegisterProviderResponse>>(PrepareAsyncregisterProviderRaw(context, request, cq));
    }
    //
    // ingestData(): Unary (non-streaming) data ingestion.
    //
    // This method sends a single IngestDataRequest and receives a single IngestDataResponse.  Validation,
    // rejection / acknowledgment, asynchronous handling, and request status reporting is otherwise the same as for the
    // ingestDataBidiStream() method.
    virtual ::grpc::Status ingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::dp::service::ingestion::IngestDataResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::IngestDataResponse>> AsyncingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::IngestDataResponse>>(AsyncingestDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::IngestDataResponse>> PrepareAsyncingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::IngestDataResponse>>(PrepareAsyncingestDataRaw(context, request, cq));
    }
    //
    // ingestDataStream(): Unidirectional client-side streaming data ingestion.
    //
    // This client-side streaming ingestion method sends a stream of IngestDataRequest messages and receives a single
    // IngestDataStreamResponse. Validation, rejection / acknowledgment, asynchronous handling, and request status
    // reporting is otherwise the same as for the ingestDataBidiStream() method, with the only difference being that
    // there is a single summary response message for the request stream instead of a stream of individual responses to
    // each request message.
    std::unique_ptr< ::grpc::ClientWriterInterface< ::dp::service::ingestion::IngestDataRequest>> ingestDataStream(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::dp::service::ingestion::IngestDataRequest>>(ingestDataStreamRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::dp::service::ingestion::IngestDataRequest>> AsyncingestDataStream(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::dp::service::ingestion::IngestDataRequest>>(AsyncingestDataStreamRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::dp::service::ingestion::IngestDataRequest>> PrepareAsyncingestDataStream(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::dp::service::ingestion::IngestDataRequest>>(PrepareAsyncingestDataStreamRaw(context, response, cq));
    }
    //
    // ingestDataBidiStream(): Bidirectional streaming data ingestion.
    //
    // The Ingestion Service performs initial validation on each IngestDataRequest in the stream, and replies immediately
    // with a IngestDataResponse message indicating acknowledgement for a valid request, or rejection of an invalid one.
    // The request is then added to a queue for async ingestion handling.
    //
    // The ingestion handling of each request in the stream is performed asynchronously.  The Ingestion Service writes
    // data from the request to the "buckets" collection in MongoDB, adding one document to the collection for each
    // "column" of data in the request's DataFrame object.
    //
    // A separate MongoDB "requestStatus" collection is used to note the processing status of each request,
    // with a document for each handled request.  The collection is keyed by the providerId and clientRequestId
    // specified in the IngestDataRequest.  This collection can be used by an administrative monitoring process
    // to detect and notify about errors in the ingestion process.
    //
    // The method returns a stream of IngestDataResponse messages, one per request.  Each response includes providerId
    // and clientRequestId for use by the client in mapping a response to the corresponding request.  The response
    // message only indicates if validation succeeded or failed.  Because ingestion handling is performed asynchronously,
    // the MongoDB "requestStatus" collection must be used to determine the success or failure of individual requests.
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>> ingestDataBidiStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>>(ingestDataBidiStreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>> AsyncingestDataBidiStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>>(AsyncingestDataBidiStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>> PrepareAsyncingestDataBidiStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>>(PrepareAsyncingestDataBidiStreamRaw(context, cq));
    }
    //
    // queryRequestStatus(): Ingestion request status query.
    //
    // This unary method sends a single QueryRequestStatusRequest and receives a single QueryRequestStatusResponse.  It
    // is used to determine the status of an individual data ingestion request, or to find data ingestion errors for a
    // specified time range.
    //
    // The QueryRequestStatusRequest message contains a list of criteria for searching by provider id, provider name,
    // request id, status, and time range. The criteria can be combined arbitrarily, but we envision three primary use
    // cases:
    //
    // 1) Query by provider id or name and request id to find the status of a specific ingestion request.
    // 2) Query by provider id or name, status (e.g., rejected or error) and time range.
    // 3) Query by status and time range without specifying a provider (e.g., "find all ingestion errors for today").
    //
    // The QueryRequestStatusResponse message payload is either an ExceptionalResult containing details about a
    // rejection or error, or a RequestStatusResult containing a list of RequestStatus messages, one for each document
    // in the MongoDB "requestStatus" collection that matches the search criteria.
    //
    // Each RequestStatus message contains details about the status of an individual ingestion request, including
    // provider id/name, request id, status enum, status message, and list of bucket ids created (documents added to the
    // MongoDB "buckets" collection).
    virtual ::grpc::Status queryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::dp::service::ingestion::QueryRequestStatusResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::QueryRequestStatusResponse>> AsyncqueryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::QueryRequestStatusResponse>>(AsyncqueryRequestStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::QueryRequestStatusResponse>> PrepareAsyncqueryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::QueryRequestStatusResponse>>(PrepareAsyncqueryRequestStatusRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      //
      // registerProvider(): Data provider registration.
      //
      // This unary method sends a single RegisterProviderRequest and receives a single RegisterProviderResponse.  It is
      // required to call this method to register a data provider before calling one of the data ingestion methods using
      // the id of that provider.
      //
      // Provider name is required in the RegisterProviderRequest, which may also contain optional metadata key/value
      // attributes describing the provider.
      //
      // The response message indicates whether or not the registration was successful.  The response payload is an
      // ExceptionalResult if the request is unsuccessful, otherwise it is a RegistrationResult that includes details about
      // the new provider including providerId (for use in calls to data ingestion methods) and a flag indicating if the
      // provider is new.  On success, if a document already exists in the MongoDB "providers" collection for the provider
      // name specified in the RegisterProviderRequest, the method returns the corresponding provider id in the response,
      // otherwise a new document is created in the "providers" collection and its id returned in the response.
      //
      // It is safe (and recommended) to call this method each time a data ingestion client is run.  If a document already
      // exists in the MongoDB providers collection for the specified provider, the attributes are updated to the values in
      // the RegisterProviderRequest.
      virtual void registerProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest* request, ::dp::service::ingestion::RegisterProviderResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void registerProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest* request, ::dp::service::ingestion::RegisterProviderResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      //
      // ingestData(): Unary (non-streaming) data ingestion.
      //
      // This method sends a single IngestDataRequest and receives a single IngestDataResponse.  Validation,
      // rejection / acknowledgment, asynchronous handling, and request status reporting is otherwise the same as for the
      // ingestDataBidiStream() method.
      virtual void ingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest* request, ::dp::service::ingestion::IngestDataResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest* request, ::dp::service::ingestion::IngestDataResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      //
      // ingestDataStream(): Unidirectional client-side streaming data ingestion.
      //
      // This client-side streaming ingestion method sends a stream of IngestDataRequest messages and receives a single
      // IngestDataStreamResponse. Validation, rejection / acknowledgment, asynchronous handling, and request status
      // reporting is otherwise the same as for the ingestDataBidiStream() method, with the only difference being that
      // there is a single summary response message for the request stream instead of a stream of individual responses to
      // each request message.
      virtual void ingestDataStream(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::ClientWriteReactor< ::dp::service::ingestion::IngestDataRequest>* reactor) = 0;
      //
      // ingestDataBidiStream(): Bidirectional streaming data ingestion.
      //
      // The Ingestion Service performs initial validation on each IngestDataRequest in the stream, and replies immediately
      // with a IngestDataResponse message indicating acknowledgement for a valid request, or rejection of an invalid one.
      // The request is then added to a queue for async ingestion handling.
      //
      // The ingestion handling of each request in the stream is performed asynchronously.  The Ingestion Service writes
      // data from the request to the "buckets" collection in MongoDB, adding one document to the collection for each
      // "column" of data in the request's DataFrame object.
      //
      // A separate MongoDB "requestStatus" collection is used to note the processing status of each request,
      // with a document for each handled request.  The collection is keyed by the providerId and clientRequestId
      // specified in the IngestDataRequest.  This collection can be used by an administrative monitoring process
      // to detect and notify about errors in the ingestion process.
      //
      // The method returns a stream of IngestDataResponse messages, one per request.  Each response includes providerId
      // and clientRequestId for use by the client in mapping a response to the corresponding request.  The response
      // message only indicates if validation succeeded or failed.  Because ingestion handling is performed asynchronously,
      // the MongoDB "requestStatus" collection must be used to determine the success or failure of individual requests.
      virtual void ingestDataBidiStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::dp::service::ingestion::IngestDataRequest,::dp::service::ingestion::IngestDataResponse>* reactor) = 0;
      //
      // queryRequestStatus(): Ingestion request status query.
      //
      // This unary method sends a single QueryRequestStatusRequest and receives a single QueryRequestStatusResponse.  It
      // is used to determine the status of an individual data ingestion request, or to find data ingestion errors for a
      // specified time range.
      //
      // The QueryRequestStatusRequest message contains a list of criteria for searching by provider id, provider name,
      // request id, status, and time range. The criteria can be combined arbitrarily, but we envision three primary use
      // cases:
      //
      // 1) Query by provider id or name and request id to find the status of a specific ingestion request.
      // 2) Query by provider id or name, status (e.g., rejected or error) and time range.
      // 3) Query by status and time range without specifying a provider (e.g., "find all ingestion errors for today").
      //
      // The QueryRequestStatusResponse message payload is either an ExceptionalResult containing details about a
      // rejection or error, or a RequestStatusResult containing a list of RequestStatus messages, one for each document
      // in the MongoDB "requestStatus" collection that matches the search criteria.
      //
      // Each RequestStatus message contains details about the status of an individual ingestion request, including
      // provider id/name, request id, status enum, status message, and list of bucket ids created (documents added to the
      // MongoDB "buckets" collection).
      virtual void queryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest* request, ::dp::service::ingestion::QueryRequestStatusResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void queryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest* request, ::dp::service::ingestion::QueryRequestStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::RegisterProviderResponse>* AsyncregisterProviderRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::RegisterProviderResponse>* PrepareAsyncregisterProviderRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::IngestDataResponse>* AsyncingestDataRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::IngestDataResponse>* PrepareAsyncingestDataRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::dp::service::ingestion::IngestDataRequest>* ingestDataStreamRaw(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::dp::service::ingestion::IngestDataRequest>* AsyncingestDataStreamRaw(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::dp::service::ingestion::IngestDataRequest>* PrepareAsyncingestDataStreamRaw(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* ingestDataBidiStreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* AsyncingestDataBidiStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* PrepareAsyncingestDataBidiStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::QueryRequestStatusResponse>* AsyncqueryRequestStatusRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::dp::service::ingestion::QueryRequestStatusResponse>* PrepareAsyncqueryRequestStatusRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status registerProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::dp::service::ingestion::RegisterProviderResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::RegisterProviderResponse>> AsyncregisterProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::RegisterProviderResponse>>(AsyncregisterProviderRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::RegisterProviderResponse>> PrepareAsyncregisterProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::RegisterProviderResponse>>(PrepareAsyncregisterProviderRaw(context, request, cq));
    }
    ::grpc::Status ingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::dp::service::ingestion::IngestDataResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::IngestDataResponse>> AsyncingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::IngestDataResponse>>(AsyncingestDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::IngestDataResponse>> PrepareAsyncingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::IngestDataResponse>>(PrepareAsyncingestDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::dp::service::ingestion::IngestDataRequest>> ingestDataStream(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::dp::service::ingestion::IngestDataRequest>>(ingestDataStreamRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::dp::service::ingestion::IngestDataRequest>> AsyncingestDataStream(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::dp::service::ingestion::IngestDataRequest>>(AsyncingestDataStreamRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::dp::service::ingestion::IngestDataRequest>> PrepareAsyncingestDataStream(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::dp::service::ingestion::IngestDataRequest>>(PrepareAsyncingestDataStreamRaw(context, response, cq));
    }
    std::unique_ptr< ::grpc::ClientReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>> ingestDataBidiStream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>>(ingestDataBidiStreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>> AsyncingestDataBidiStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>>(AsyncingestDataBidiStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>> PrepareAsyncingestDataBidiStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>>(PrepareAsyncingestDataBidiStreamRaw(context, cq));
    }
    ::grpc::Status queryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::dp::service::ingestion::QueryRequestStatusResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::QueryRequestStatusResponse>> AsyncqueryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::QueryRequestStatusResponse>>(AsyncqueryRequestStatusRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::QueryRequestStatusResponse>> PrepareAsyncqueryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::QueryRequestStatusResponse>>(PrepareAsyncqueryRequestStatusRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void registerProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest* request, ::dp::service::ingestion::RegisterProviderResponse* response, std::function<void(::grpc::Status)>) override;
      void registerProvider(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest* request, ::dp::service::ingestion::RegisterProviderResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest* request, ::dp::service::ingestion::IngestDataResponse* response, std::function<void(::grpc::Status)>) override;
      void ingestData(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest* request, ::dp::service::ingestion::IngestDataResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ingestDataStream(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::ClientWriteReactor< ::dp::service::ingestion::IngestDataRequest>* reactor) override;
      void ingestDataBidiStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::dp::service::ingestion::IngestDataRequest,::dp::service::ingestion::IngestDataResponse>* reactor) override;
      void queryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest* request, ::dp::service::ingestion::QueryRequestStatusResponse* response, std::function<void(::grpc::Status)>) override;
      void queryRequestStatus(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest* request, ::dp::service::ingestion::QueryRequestStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::RegisterProviderResponse>* AsyncregisterProviderRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::RegisterProviderResponse>* PrepareAsyncregisterProviderRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::RegisterProviderRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::IngestDataResponse>* AsyncingestDataRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::IngestDataResponse>* PrepareAsyncingestDataRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::IngestDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::dp::service::ingestion::IngestDataRequest>* ingestDataStreamRaw(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response) override;
    ::grpc::ClientAsyncWriter< ::dp::service::ingestion::IngestDataRequest>* AsyncingestDataStreamRaw(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::dp::service::ingestion::IngestDataRequest>* PrepareAsyncingestDataStreamRaw(::grpc::ClientContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* ingestDataBidiStreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* AsyncingestDataBidiStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* PrepareAsyncingestDataBidiStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::QueryRequestStatusResponse>* AsyncqueryRequestStatusRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::dp::service::ingestion::QueryRequestStatusResponse>* PrepareAsyncqueryRequestStatusRaw(::grpc::ClientContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_registerProvider_;
    const ::grpc::internal::RpcMethod rpcmethod_ingestData_;
    const ::grpc::internal::RpcMethod rpcmethod_ingestDataStream_;
    const ::grpc::internal::RpcMethod rpcmethod_ingestDataBidiStream_;
    const ::grpc::internal::RpcMethod rpcmethod_queryRequestStatus_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    //
    // registerProvider(): Data provider registration.
    //
    // This unary method sends a single RegisterProviderRequest and receives a single RegisterProviderResponse.  It is
    // required to call this method to register a data provider before calling one of the data ingestion methods using
    // the id of that provider.
    //
    // Provider name is required in the RegisterProviderRequest, which may also contain optional metadata key/value
    // attributes describing the provider.
    //
    // The response message indicates whether or not the registration was successful.  The response payload is an
    // ExceptionalResult if the request is unsuccessful, otherwise it is a RegistrationResult that includes details about
    // the new provider including providerId (for use in calls to data ingestion methods) and a flag indicating if the
    // provider is new.  On success, if a document already exists in the MongoDB "providers" collection for the provider
    // name specified in the RegisterProviderRequest, the method returns the corresponding provider id in the response,
    // otherwise a new document is created in the "providers" collection and its id returned in the response.
    //
    // It is safe (and recommended) to call this method each time a data ingestion client is run.  If a document already
    // exists in the MongoDB providers collection for the specified provider, the attributes are updated to the values in
    // the RegisterProviderRequest.
    virtual ::grpc::Status registerProvider(::grpc::ServerContext* context, const ::dp::service::ingestion::RegisterProviderRequest* request, ::dp::service::ingestion::RegisterProviderResponse* response);
    //
    // ingestData(): Unary (non-streaming) data ingestion.
    //
    // This method sends a single IngestDataRequest and receives a single IngestDataResponse.  Validation,
    // rejection / acknowledgment, asynchronous handling, and request status reporting is otherwise the same as for the
    // ingestDataBidiStream() method.
    virtual ::grpc::Status ingestData(::grpc::ServerContext* context, const ::dp::service::ingestion::IngestDataRequest* request, ::dp::service::ingestion::IngestDataResponse* response);
    //
    // ingestDataStream(): Unidirectional client-side streaming data ingestion.
    //
    // This client-side streaming ingestion method sends a stream of IngestDataRequest messages and receives a single
    // IngestDataStreamResponse. Validation, rejection / acknowledgment, asynchronous handling, and request status
    // reporting is otherwise the same as for the ingestDataBidiStream() method, with the only difference being that
    // there is a single summary response message for the request stream instead of a stream of individual responses to
    // each request message.
    virtual ::grpc::Status ingestDataStream(::grpc::ServerContext* context, ::grpc::ServerReader< ::dp::service::ingestion::IngestDataRequest>* reader, ::dp::service::ingestion::IngestDataStreamResponse* response);
    //
    // ingestDataBidiStream(): Bidirectional streaming data ingestion.
    //
    // The Ingestion Service performs initial validation on each IngestDataRequest in the stream, and replies immediately
    // with a IngestDataResponse message indicating acknowledgement for a valid request, or rejection of an invalid one.
    // The request is then added to a queue for async ingestion handling.
    //
    // The ingestion handling of each request in the stream is performed asynchronously.  The Ingestion Service writes
    // data from the request to the "buckets" collection in MongoDB, adding one document to the collection for each
    // "column" of data in the request's DataFrame object.
    //
    // A separate MongoDB "requestStatus" collection is used to note the processing status of each request,
    // with a document for each handled request.  The collection is keyed by the providerId and clientRequestId
    // specified in the IngestDataRequest.  This collection can be used by an administrative monitoring process
    // to detect and notify about errors in the ingestion process.
    //
    // The method returns a stream of IngestDataResponse messages, one per request.  Each response includes providerId
    // and clientRequestId for use by the client in mapping a response to the corresponding request.  The response
    // message only indicates if validation succeeded or failed.  Because ingestion handling is performed asynchronously,
    // the MongoDB "requestStatus" collection must be used to determine the success or failure of individual requests.
    virtual ::grpc::Status ingestDataBidiStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::dp::service::ingestion::IngestDataResponse, ::dp::service::ingestion::IngestDataRequest>* stream);
    //
    // queryRequestStatus(): Ingestion request status query.
    //
    // This unary method sends a single QueryRequestStatusRequest and receives a single QueryRequestStatusResponse.  It
    // is used to determine the status of an individual data ingestion request, or to find data ingestion errors for a
    // specified time range.
    //
    // The QueryRequestStatusRequest message contains a list of criteria for searching by provider id, provider name,
    // request id, status, and time range. The criteria can be combined arbitrarily, but we envision three primary use
    // cases:
    //
    // 1) Query by provider id or name and request id to find the status of a specific ingestion request.
    // 2) Query by provider id or name, status (e.g., rejected or error) and time range.
    // 3) Query by status and time range without specifying a provider (e.g., "find all ingestion errors for today").
    //
    // The QueryRequestStatusResponse message payload is either an ExceptionalResult containing details about a
    // rejection or error, or a RequestStatusResult containing a list of RequestStatus messages, one for each document
    // in the MongoDB "requestStatus" collection that matches the search criteria.
    //
    // Each RequestStatus message contains details about the status of an individual ingestion request, including
    // provider id/name, request id, status enum, status message, and list of bucket ids created (documents added to the
    // MongoDB "buckets" collection).
    virtual ::grpc::Status queryRequestStatus(::grpc::ServerContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest* request, ::dp::service::ingestion::QueryRequestStatusResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_registerProvider : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_registerProvider() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_registerProvider() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerProvider(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::RegisterProviderRequest* /*request*/, ::dp::service::ingestion::RegisterProviderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestregisterProvider(::grpc::ServerContext* context, ::dp::service::ingestion::RegisterProviderRequest* request, ::grpc::ServerAsyncResponseWriter< ::dp::service::ingestion::RegisterProviderResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ingestData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ingestData() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ingestData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestData(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::IngestDataRequest* /*request*/, ::dp::service::ingestion::IngestDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestingestData(::grpc::ServerContext* context, ::dp::service::ingestion::IngestDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::dp::service::ingestion::IngestDataResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ingestDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ingestDataStream() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_ingestDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::dp::service::ingestion::IngestDataRequest>* /*reader*/, ::dp::service::ingestion::IngestDataStreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestingestDataStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::dp::service::ingestion::IngestDataStreamResponse, ::dp::service::ingestion::IngestDataRequest>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ingestDataBidiStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ingestDataBidiStream() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_ingestDataBidiStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataBidiStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::dp::service::ingestion::IngestDataResponse, ::dp::service::ingestion::IngestDataRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestingestDataBidiStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::dp::service::ingestion::IngestDataResponse, ::dp::service::ingestion::IngestDataRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_queryRequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_queryRequestStatus() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_queryRequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status queryRequestStatus(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::QueryRequestStatusRequest* /*request*/, ::dp::service::ingestion::QueryRequestStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestqueryRequestStatus(::grpc::ServerContext* context, ::dp::service::ingestion::QueryRequestStatusRequest* request, ::grpc::ServerAsyncResponseWriter< ::dp::service::ingestion::QueryRequestStatusResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_registerProvider<WithAsyncMethod_ingestData<WithAsyncMethod_ingestDataStream<WithAsyncMethod_ingestDataBidiStream<WithAsyncMethod_queryRequestStatus<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_registerProvider : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_registerProvider() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::dp::service::ingestion::RegisterProviderRequest, ::dp::service::ingestion::RegisterProviderResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dp::service::ingestion::RegisterProviderRequest* request, ::dp::service::ingestion::RegisterProviderResponse* response) { return this->registerProvider(context, request, response); }));}
    void SetMessageAllocatorFor_registerProvider(
        ::grpc::MessageAllocator< ::dp::service::ingestion::RegisterProviderRequest, ::dp::service::ingestion::RegisterProviderResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dp::service::ingestion::RegisterProviderRequest, ::dp::service::ingestion::RegisterProviderResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_registerProvider() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerProvider(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::RegisterProviderRequest* /*request*/, ::dp::service::ingestion::RegisterProviderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* registerProvider(
      ::grpc::CallbackServerContext* /*context*/, const ::dp::service::ingestion::RegisterProviderRequest* /*request*/, ::dp::service::ingestion::RegisterProviderResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ingestData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ingestData() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dp::service::ingestion::IngestDataRequest* request, ::dp::service::ingestion::IngestDataResponse* response) { return this->ingestData(context, request, response); }));}
    void SetMessageAllocatorFor_ingestData(
        ::grpc::MessageAllocator< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ingestData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestData(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::IngestDataRequest* /*request*/, ::dp::service::ingestion::IngestDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ingestData(
      ::grpc::CallbackServerContext* /*context*/, const ::dp::service::ingestion::IngestDataRequest* /*request*/, ::dp::service::ingestion::IngestDataResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ingestDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ingestDataStream() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataStreamResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, ::dp::service::ingestion::IngestDataStreamResponse* response) { return this->ingestDataStream(context, response); }));
    }
    ~WithCallbackMethod_ingestDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::dp::service::ingestion::IngestDataRequest>* /*reader*/, ::dp::service::ingestion::IngestDataStreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::dp::service::ingestion::IngestDataRequest>* ingestDataStream(
      ::grpc::CallbackServerContext* /*context*/, ::dp::service::ingestion::IngestDataStreamResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ingestDataBidiStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ingestDataBidiStream() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ingestDataBidiStream(context); }));
    }
    ~WithCallbackMethod_ingestDataBidiStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataBidiStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::dp::service::ingestion::IngestDataResponse, ::dp::service::ingestion::IngestDataRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* ingestDataBidiStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_queryRequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_queryRequestStatus() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::dp::service::ingestion::QueryRequestStatusRequest, ::dp::service::ingestion::QueryRequestStatusResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::dp::service::ingestion::QueryRequestStatusRequest* request, ::dp::service::ingestion::QueryRequestStatusResponse* response) { return this->queryRequestStatus(context, request, response); }));}
    void SetMessageAllocatorFor_queryRequestStatus(
        ::grpc::MessageAllocator< ::dp::service::ingestion::QueryRequestStatusRequest, ::dp::service::ingestion::QueryRequestStatusResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::dp::service::ingestion::QueryRequestStatusRequest, ::dp::service::ingestion::QueryRequestStatusResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_queryRequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status queryRequestStatus(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::QueryRequestStatusRequest* /*request*/, ::dp::service::ingestion::QueryRequestStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* queryRequestStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::dp::service::ingestion::QueryRequestStatusRequest* /*request*/, ::dp::service::ingestion::QueryRequestStatusResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_registerProvider<WithCallbackMethod_ingestData<WithCallbackMethod_ingestDataStream<WithCallbackMethod_ingestDataBidiStream<WithCallbackMethod_queryRequestStatus<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_registerProvider : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_registerProvider() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_registerProvider() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerProvider(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::RegisterProviderRequest* /*request*/, ::dp::service::ingestion::RegisterProviderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ingestData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ingestData() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ingestData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestData(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::IngestDataRequest* /*request*/, ::dp::service::ingestion::IngestDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ingestDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ingestDataStream() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_ingestDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::dp::service::ingestion::IngestDataRequest>* /*reader*/, ::dp::service::ingestion::IngestDataStreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ingestDataBidiStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ingestDataBidiStream() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_ingestDataBidiStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataBidiStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::dp::service::ingestion::IngestDataResponse, ::dp::service::ingestion::IngestDataRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_queryRequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_queryRequestStatus() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_queryRequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status queryRequestStatus(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::QueryRequestStatusRequest* /*request*/, ::dp::service::ingestion::QueryRequestStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_registerProvider : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_registerProvider() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_registerProvider() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerProvider(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::RegisterProviderRequest* /*request*/, ::dp::service::ingestion::RegisterProviderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestregisterProvider(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ingestData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ingestData() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ingestData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestData(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::IngestDataRequest* /*request*/, ::dp::service::ingestion::IngestDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestingestData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ingestDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ingestDataStream() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_ingestDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::dp::service::ingestion::IngestDataRequest>* /*reader*/, ::dp::service::ingestion::IngestDataStreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestingestDataStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(2, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ingestDataBidiStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ingestDataBidiStream() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_ingestDataBidiStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataBidiStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::dp::service::ingestion::IngestDataResponse, ::dp::service::ingestion::IngestDataRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestingestDataBidiStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(3, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_queryRequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_queryRequestStatus() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_queryRequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status queryRequestStatus(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::QueryRequestStatusRequest* /*request*/, ::dp::service::ingestion::QueryRequestStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestqueryRequestStatus(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_registerProvider : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_registerProvider() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->registerProvider(context, request, response); }));
    }
    ~WithRawCallbackMethod_registerProvider() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status registerProvider(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::RegisterProviderRequest* /*request*/, ::dp::service::ingestion::RegisterProviderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* registerProvider(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ingestData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ingestData() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ingestData(context, request, response); }));
    }
    ~WithRawCallbackMethod_ingestData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestData(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::IngestDataRequest* /*request*/, ::dp::service::ingestion::IngestDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ingestData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ingestDataStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ingestDataStream() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, ::grpc::ByteBuffer* response) { return this->ingestDataStream(context, response); }));
    }
    ~WithRawCallbackMethod_ingestDataStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::dp::service::ingestion::IngestDataRequest>* /*reader*/, ::dp::service::ingestion::IngestDataStreamResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerReadReactor< ::grpc::ByteBuffer>* ingestDataStream(
      ::grpc::CallbackServerContext* /*context*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ingestDataBidiStream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ingestDataBidiStream() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->ingestDataBidiStream(context); }));
    }
    ~WithRawCallbackMethod_ingestDataBidiStream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ingestDataBidiStream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::dp::service::ingestion::IngestDataResponse, ::dp::service::ingestion::IngestDataRequest>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* ingestDataBidiStream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_queryRequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_queryRequestStatus() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->queryRequestStatus(context, request, response); }));
    }
    ~WithRawCallbackMethod_queryRequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status queryRequestStatus(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::QueryRequestStatusRequest* /*request*/, ::dp::service::ingestion::QueryRequestStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* queryRequestStatus(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_registerProvider : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_registerProvider() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dp::service::ingestion::RegisterProviderRequest, ::dp::service::ingestion::RegisterProviderResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dp::service::ingestion::RegisterProviderRequest, ::dp::service::ingestion::RegisterProviderResponse>* streamer) {
                       return this->StreamedregisterProvider(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_registerProvider() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status registerProvider(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::RegisterProviderRequest* /*request*/, ::dp::service::ingestion::RegisterProviderResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedregisterProvider(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dp::service::ingestion::RegisterProviderRequest,::dp::service::ingestion::RegisterProviderResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ingestData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ingestData() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dp::service::ingestion::IngestDataRequest, ::dp::service::ingestion::IngestDataResponse>* streamer) {
                       return this->StreamedingestData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ingestData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ingestData(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::IngestDataRequest* /*request*/, ::dp::service::ingestion::IngestDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedingestData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dp::service::ingestion::IngestDataRequest,::dp::service::ingestion::IngestDataResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_queryRequestStatus : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_queryRequestStatus() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::dp::service::ingestion::QueryRequestStatusRequest, ::dp::service::ingestion::QueryRequestStatusResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::dp::service::ingestion::QueryRequestStatusRequest, ::dp::service::ingestion::QueryRequestStatusResponse>* streamer) {
                       return this->StreamedqueryRequestStatus(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_queryRequestStatus() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status queryRequestStatus(::grpc::ServerContext* /*context*/, const ::dp::service::ingestion::QueryRequestStatusRequest* /*request*/, ::dp::service::ingestion::QueryRequestStatusResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedqueryRequestStatus(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::dp::service::ingestion::QueryRequestStatusRequest,::dp::service::ingestion::QueryRequestStatusResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_registerProvider<WithStreamedUnaryMethod_ingestData<WithStreamedUnaryMethod_queryRequestStatus<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_registerProvider<WithStreamedUnaryMethod_ingestData<WithStreamedUnaryMethod_queryRequestStatus<Service > > > StreamedService;
};

}  // namespace ingestion
}  // namespace service
}  // namespace dp


#endif  // GRPC_ingestion_2eproto__INCLUDED
